#9 Sprint 9
valer0n3/java-filmorate pull request #1
Opened 2022-10-31 22:26 UTC by valer0n3

2022-11-01 10:59 UTC, AnastasiyaFomkina requested changes

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
_Опционально_
Можно удалить проверку, если добавить полю description аннотацию `@Size(max = 200)` - параметр `max` - это максимальное количество символов в строке. Также у `@Size` есть параметр `min` - минимальное количество символов

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void checkDateOfBirth(LocalDate birthday) {
_Опционально_
Можно заменить проверку на аннотацию `@PastOrPresent` для поля _birthday_ - она валидирует, что дата должна быть в прошлом или не позже, чем сейчас

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (login.contains(" ")) {
`" "` - это пробел или, если использовать [regexp](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5_%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F), то `\\s`. Ниже нужно поправить логирование и мессадж ошибки на `space` 😉

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public boolean checkIfNameIsEmpty(User user) {
Все проверки используются только внутри данного класса, лучше присвоить им максимально строгий модификатор доступа, чтобы не было возможности нечаянно их подменить

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private boolean checkIfUserIdExists(int id) {
лучше заменить на встроенный метод мапы : [hashmap.containsKey(Object key)](https://www.programiz.com/java-programming/library/hashmap/containskey)

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Молодец, что добавил тесты 👍

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void tearDown() {
Лучше удалить весь блок `@AfterEach`, так как в нем сейчас ничего не происходит

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    @AfterEach
Здесь тоже лучше удалить блок

2022-11-01 10:59 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +                , "Return incorrect False when user's name isBlanked");
Лучше оставлять запятую на предыдущей строке. Так код удобнее и проще читать

2022-11-01 19:53 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Спасибо. Настройки IDEA поменял. wildcards в импорте убрал.

2022-11-01 20:27 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
Аннотация @Size(max = 200) добавлена.

2022-11-01 20:35 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void checkDateOfBirth(LocalDate birthday) {
Аннотация @PastOrPresent  была добавлена.

2022-11-01 20:44 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (login.contains(" ")) {
" " изменено на \s.

2022-11-01 20:53 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public boolean checkIfNameIsEmpty(User user) {
Модификатор доступа изменен на default, а не на private, чтобы запускались тесты.

2022-11-01 20:57 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private boolean checkIfUserIdExists(int id) {
Измененения внесены.

2022-11-01 20:59 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void tearDown() {
Блок @AfterEach удален.

2022-11-01 20:59 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    @AfterEach
Блок @AfterEach удален.

2022-11-01 21:02 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +                , "Return incorrect False when user's name isBlanked");
Исправлено.

2022-11-02 11:50 UTC, AnastasiyaFomkina approved these changes

2022-11-02 11:59 UTC, merged