#10 Sprint 10
valer0n3/java-filmorate pull request #2
Opened 2022-11-16 14:05 UTC by valer0n3

2022-11-16 18:28 UTC, AnastasiyaFomkina requested changes

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
_Опционально_
Так как мы используем `lombok` в приложении, проще будет доверить инжект полей ему:
https://www.baeldung.com/spring-injection-lombok

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET .../users/{id}
Похоже на лишний комментарий

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        //TODO add implmentation
Лучше не оставлять в коде выполненные `TODO`

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    String description;
Не хватает модификаторов доступа у полей класса

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
_Опционально_
Можно заменить на [@AllArgsConstructor](https://www.educative.io/answers/what-is-the-allargsconstructor-annotation-in-lombok)

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    final UserStorage userStorage;
Не хватает модификатора доступа

2022-11-16 18:28 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        System.out.println("******: " + likedFilm.setOfLikes);
Похоже, использовалось для отладки - лучше удалить или использовать логирование

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidationService.java
> +    void checkFilmDuration(int duration) {
Можно использовать аннотацию [@Positive](https://www.baeldung.com/javax-validation#:~:text=null%20or%20whitespace.-,%40Positive,-and%20%40PositiveOrZero%20apply) над полем модели, она автоматически сгенерирует валидацию, что значение должно быть больше 0

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        System.out.println(userFriend.getSetOfFriends());
Лучше всю печать заменить на логирование

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void checkIfSetOfFriendsIsEmpty(User user, User userFriend) {
Проверка нигде не используется

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void checkIfUserObjectIsNull(User user) {
Если метод используется только внутри класса, лучше проставлять ему модификатор доступа `private`. Поправь, пожалуйста подобные случаи по всему проекту

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidationService.java
> +        if (Pattern.matches(".*\\s.*", login)) {
_Опционально_
Можно заменить проверку на аннотацию [@Pattern](https://reflectoring.io/bean-validation-with-spring-boot/#:~:text=a%20certain%20value.-,%40Pattern%3A,-to%20say%20that)

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
👍

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private final static LocalDate EARLIEST_RELEASE_DATE = LocalDate.parse("1895-12-28");
Константа нигде не используется

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        for (long filmMapKey : filmMap.keySet()) {
Лучше заменить перебор всех элементов на  [java.util.HashMap.containsKey()](https://www.geeksforgeeks.org/hashmap-containskey-method-in-java/)

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Set<Long> getCommonFriendList(long id) {
Метод нигде не исползуется

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        //TODO change implementation
Лучше удалить

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage {
👍

2022-11-16 18:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        checkIfUserObjectExists(user);
Код со строе 29-30 и 31-32 дублируется ниже
Получение по id и проверку можно вынести в отдельные методы, а здесь уже использовать их. Так можно избавиться от дублирования кода и сделать его более читаемым.

2022-11-16 19:09 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Анастасия, можно оставить как есть? Я как-то не особо доверяю Lombok.

2022-11-16 19:11 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET .../users/{id}
Анастасия, я извиняюсь за весь этот мусор. Я удалил все лишние комментарии, тестовые выводы, поправил импорты перед отправкой. Но не закомитил последние изменения и сделал pull request. Из-за этого все это выглядит таким образом. Мне очень стыдно за это:(

2022-11-16 19:12 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    String description;
Изменения внесены.

2022-11-16 19:14 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Если можно, то оставлю это без изменений.

2022-11-16 19:16 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        for (long filmMapKey : filmMap.keySet()) {
Изменения внесены.

2022-11-16 19:18 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Set<Long> getCommonFriendList(long id) {
Исправлено. 
Исправил до отправки пул реквеста, но не закомитил:(

2022-11-16 19:21 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        //TODO add implmentation
Исправлено:(

2022-11-16 19:22 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        //TODO change implementation
Вы даже не представляете как мне стыдно за то что не закомитил последние изменения и запушил на гитхаб:(

2022-11-16 19:44 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        checkIfUserObjectExists(user);
Методы likeFilm() и deleteFilmsLike() оптимизированы.

2022-11-17 06:29 UTC, AnastasiyaFomkina approved these changes

2022-11-17 06:29 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Оставить как есть можно. А что конкретно не так с lombok, почему ты ему не доверяешь?

2022-11-17 06:29 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    //GET .../users/{id}
Ничего страшного, у всех бывает)

2022-11-17 06:51 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
В плане аннотации @AllArgsConstructor все понятно - генерируется конструктор со всеми полями. Наверное здесь логично его применить. Я не знал, что в таком случае также происходит инжект полей. Спасибо за рекомендацию. 
Но если использовать аннотацию @Data, которая применяет @RequiredArgsConstructor для генерации конструктором - то не совсем понятно какие конструкторы будут созданы и как посмотреть какие конструкторы lombok создал.

2022-11-17 16:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Вот отличная [статья](https://habr.com/ru/company/piter/blog/676394/), в который подробно рассказано, что генерирует `lombok` при применения той или иной аннотации. 
Конкретно в случае `@Data` `lombok` сгенерирует конструктор, в котором будут только поля класса с модификатором `final` или аннотацией `@NotNull`

2022-12-05 08:00 UTC, merged