#11 Sprint 11
valer0n3/java-filmorate pull request #3
Opened 2022-12-12 20:41 UTC by valer0n3

2022-12-13 16:27 UTC, afomkina requested changes

2022-12-13 16:27 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film GetFilmFromId(long id) {
По code-style методы принять именовать в camelCase, поправь, пожалуйста

2022-12-13 16:27 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    @Autowired
_Опционально_
Предлагаю использовать [@RequiredArgsConstructor](https://www.baeldung.com/spring-injection-lombok) от lombok. Он поможет не только избавиться от однотипного кода, но и его сократить

2022-12-13 16:27 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidationService.java
> +        System.out.println("***_____*: " + film.getGenres());
Лучше использовать логирование или удалить

2022-12-13 16:27 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidationService.java
> +    private void DeleteDuplicatedGenres(Film film) {
Нужно переименовать метод по code-style

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidationService.java
> +        List<User> us = userStorage.getAllUsers();
По code-style принято именовать переменные "осмысленно", сокращения и однобуквенные переменные ухудшают читаемость кода. Поправь, пожалуйста

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[]{"film_id"});
Лучше не сокращать названия переменных

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Лучше удалять креды, которые не используются

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorageTest.java
> +class GenreDbStorageTest {
Добавь, пожалуйста, тест класса `FilmDbStorage`

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/service/UserValidationServiceTest.java
> -class UserValidationServiceTest {
_Опционально_
Лучше не удалять тесты валидации, а поправить в соответствии с новым функционалом. Базу можно подключить, как в тестах storage классов

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return listOfFilms;
Можно сразу возвращать результат query:
```suggestion
        return jdbcTemplate.query(sqlQueryFilmsSelect, (resultSet, rowNumber) -> mapRowToFilm(resultSet));
```

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return genreList;
И здесь тоже

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                                resultSet.getString(("GENRE.NAME"))), film_id);
`(("GENRE.NAME")))` - лишние скобочки

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      final UserStorage userStorage;
Не хватает модификатора доступа

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        return (sqlRowSet.next());
Лишние скобочки

2022-12-13 16:27 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> +        String sqlRequest = "delete  from USERS";
Лишний пробел 
```suggestion
        String sqlRequest = "delete from USERS";
```

2022-12-14 08:17 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film GetFilmFromId(long id) {
Исправлено.

2022-12-14 08:47 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    @Autowired
Исправлено во всем проекте.

2022-12-14 08:54 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidationService.java
> +        System.out.println("***_____*: " + film.getGenres());
Ненужные sout удалены.

2022-12-14 08:55 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidationService.java
> +    private void DeleteDuplicatedGenres(Film film) {
Исправлено.

2022-12-14 08:58 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidationService.java
> +        List<User> us = userStorage.getAllUsers();
Удал ненужную переменную, т.к. использовалась в выводе на экран для проверки.

2022-12-14 09:28 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[]{"film_id"});
Переменная переименована.

2022-12-14 09:29 UTC, valer0n3 commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Анастасия, можно не удалять данную строку, т.к. при написании использовал сохранение БД в файл для проверок?

2022-12-14 11:09 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return listOfFilms;
Исправлено.

2022-12-14 11:10 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return genreList;
Исправлено.

2022-12-14 11:11 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                                resultSet.getString(("GENRE.NAME"))), film_id);
Исправлено.

2022-12-14 11:13 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      final UserStorage userStorage;
Исправлено.

2022-12-14 11:15 UTC, valer0n3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        return (sqlRowSet.next());
Исправлено.

2022-12-14 11:16 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
> +        String sqlRequest = "delete  from USERS";
Исправлено.

2022-12-14 12:42 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorageTest.java
> +class GenreDbStorageTest {
Добавлено несколько тестов.

2022-12-14 12:42 UTC, valer0n3 commented on src/test/java/ru/yandex/practicum/filmorate/service/UserValidationServiceTest.java
> -class UserValidationServiceTest {
Тесты валидации восстановлены и исправлены.

2022-12-15 07:56 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Окей

2022-12-15 07:56 UTC, AnastasiyaFomkina approved these changes

2022-12-15 10:04 UTC, merged